### ISSUE TITLE
Compilation on Linux

### ISSUE THREAD

**Issue by qri-hub** [4gsim/4Gsim#5]
Hi, I don't know if there is still some help here but I'll give it a shot. 
I am trying to compile 4GSIM but it seems to fail. 
what I've done : 
- make makefiles 
- make make 
but this gives me an error of headers not found, and I don't know of to modify the makefiles (given they are created by op_make.
The error : 

```
MSGC: world/powercontrol/PowerControlMessages.msg
applications/dhcp/DHCPClient.cc
In file included from applications/dhcp/DHCPClient.cc:19:0:
applications/dhcp/DHCPClient.h:23:31: fatal error: NotificationBoard.h: No such file or directory
compilation terminated.
Makefile:759: recipe for target '../out/gcc-debug/src/applications/dhcp/DHCPClient.o' failed
make[1]: *** [../out/gcc-debug/src/applications/dhcp/DHCPClient.o] Error 1
make[1]: Leaving directory '/home/scaven/4Gsim-master/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by 4gsim** [comment]
Hi,

Sorry, but I did not work on it for a long time. I don't know what's the
status of the project and frankly I kinda forgot C++.

Br,
Calin

**Comment by qri-hub** [comment]
Okay no problems.

Regards,
